name: CI-CD

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:

  # 1️⃣ LINT + INSTALL
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm install
      - run: npm run lint || echo "pas de lint configuré"

  # 2️⃣ TESTS
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm install
      - run: npm test || echo "pas de tests"

  # 2.5️⃣ SONARQUBE ANALYSE
  sonar:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: SonarQube
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # 3️⃣ BUILD DOCKER
  docker:
    needs: [lint, test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login GitHub Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/projet-ecole2.0:latest
            ghcr.io/${{ github.repository_owner }}/projet-ecole2.0:${{ github.sha }}

  # 4️⃣ DEPLOIEMENT STAGING
  deploy-staging:
    needs: docker
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
      - run: echo "Déploiement staging (simulation)"

  # 5️⃣ DEPLOIEMENT PROD (TAG)
  deploy-prod:
    needs: docker
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - run: echo "Déploiement production (validation requise)"

        